### ISSUE TITLE
Review deployment pipeline for services that deploy to multiple cluster types in an environment

### ISSUE THREAD

**Issue by efinlay24** [Financial-Times/k8s-pipeline-library#55]
When apps are shared between stacks, this happens:
https://upp-k8s-jenkins.in.ft.com/job/k8s-deployment/job/apps-deployment/job/upp-aggregate-healthcheck-auto-deploy/job/tags%252F1.5.0-k8s-resiliency-rc3/

https://trello.com/c/7MelnKRo/111-review-deployment-pipeline-for-services-that-deploy-to-multiple-cluster-types-in-an-environment

**Comment by sbuliarca** [comment]
We mitigated this by using a different Jenkinsfile per stack as it seems Jenkins supports specifying the source script for a multibranch pipeline:
Example jobs are:
- https://upp-k8s-jenkins.in.ft.com/job/k8s-deployment/job/apps-deployment/job/content-k8s-prometheus-auto-deploy/
- https://upp-k8s-jenkins.in.ft.com/job/k8s-deployment/job/pac-apps-deployment/job/pac-content-k8s-prometheus-auto-deploy/

And The PR was: https://github.com/Financial-Times/content-k8s-prometheus/pull/5
