### ISSUE TITLE
Documentation for Jenkins pipeline

### ISSUE THREAD

**Issue by efinlay24** [Financial-Times/k8s-pipeline-library#56]
https://trello.com/c/kAsGFfCg/50-documentation-for-jenkins-pipeline

**Comment by sbuliarca** [comment]
Used images:

![screen shot 2018-08-27 at 2 39 44 pm](https://user-images.githubusercontent.com/8848332/44658096-23177400-aa08-11e8-8607-af78a4288d06.png)

**Comment by sbuliarca** [comment]
<img width="981" alt="screen shot 2018-08-27 at 3 23 47 pm" src="https://user-images.githubusercontent.com/8848332/44659662-a8515780-aa0d-11e8-8592-c215b67922cc.png">

**Comment by sbuliarca** [comment]
<img width="956" alt="screen shot 2018-08-27 at 3 24 22 pm" src="https://user-images.githubusercontent.com/8848332/44659677-b43d1980-aa0d-11e8-8288-51c446d06bf3.png">

**Comment by sbuliarca** [comment]
Handled in several tech debt sessions:  https://trello.com/c/3VITuRNt/134-tech-debt-kubernetes-deployment-documentation
