### ISSUE TITLE
Upgrade Helm

### ISSUE THREAD

**Issue by efinlay24** [Financial-Times/k8s-pipeline-library#57]
I created an issue for helm here: https://github.com/kubernetes/helm/issues/2828

---

Someone created a PR for solving this issue in helm, I tested it and it works feat(helm): Add --col-width to helm list and helm history.

Will follow up when helm is released with this feature.

https://trello.com/c/SUfSAZpI/44-upgrade-helm

**Comment by david-smith-ft** [comment]
The issue with multiple releases showing in `helm list` when it fails to deploy (UI bug, it rolls back correctly) should have been fixed in 2.8, so it would be useful to have an upgrade for this (I've just deleted 29 broken deployments from k8s-delivery-eu)
